// Seed catalog. The five vessels/packages and their prices come from the live
// Rezdy catalog #639381. Extra prices are placeholders — they are meant to be
// edited from the admin, not from this file.

export const settings = {
  brand: 'Love Cloud Tours & Weddings',
  productLine: 'Roatan Private Yacht Getaways',
  currency: 'USD',
  depositPct: 30,
  balanceDueHours: 48,
  contactEmail: 'reservations@lovecloudroatan.com',
  contactPhone: '+1 (702) 419-4681',
  whatsapp: '+1 (702) 419-4681',
  departurePoint: 'The Verandas at Pristine Bay, Roatán, Bay Islands, Honduras',
  departureNote: 'Meet us at the dock below The Verandas at Pristine Bay. Free parking, and the crew will be waiting with your name on the board.',
  cancellationPolicy:
    'Free cancellation up to 7 days before departure. Within 7 days the deposit is non-refundable. Trips cancelled by us for weather are fully refunded or rescheduled at no cost.',
  instantBooking: true,
}

export const vessels = [
  {
    id: 'v_speedboat_day',
    slug: 'private-speedboat-full-day',
    name: 'Private Luxury Full Day Speedboat Adventure',
    boatName: "Li'l Knotty",
    tagline: 'Twin 200s, a shaded T-top, and the whole island at your pace.',
    description:
      "Li'l Knotty is our centre console — twin 200 hp Suzukis, shade over the helm and a hull that gets you to the far side of the island before the crowds. We run the day at your pace: snorkel the reef, get pulled on the tube, and swim off the sand at Pigeon Cay.",
    photo: '/media/lilknotty-running',
    gallery: ['/media/lilknotty-marina', '/media/lilknotty-dusk', '/media/lilknotty-running-wide'],
    type: 'day',
    durationLabel: '8 hours',
    basePrice: 995,
    priceUnit: 'flat',
    minNights: 0,
    capacityMin: 1,
    capacityMax: 10,
    includes: [
      "Li'l Knotty, a private centre console with twin 200 hp outboards",
      'Private captain and crew',
      'Shaded T-top over the helm',
      'Bow seating and cushioned casting deck',
      'Snorkeling gear and guided reef stop',
      'Tubing',
      'Swim stop at Pigeon Cay',
      'All-inclusive food and drinks',
      'Fuel and park fees',
    ],
    heroEmoji: '🚤',
    accent: '#1C6A72',
    active: true,
    sortOrder: 1,
  },
  {
    id: 'v_yacht_day',
    slug: 'private-yacht-full-day',
    name: "Private Luxury Full Day Yacht Charter",
    boatName: 'Knotty',
    tagline: "47 feet of shade, air conditioning and open water.",
    description:
      "Lounge in luxury and enjoy proper pampering aboard Knotty, our private 47' yacht, tailored just for you and your group. Teak cockpit under canvas shade, air-conditioned cabin when the sun gets serious, a tender on the swim platform for the shallow stuff, and a captain who knows every reef worth stopping at.",
    photo: '/media/knotty-stern',
    gallery: ['/media/knotty-cockpit-wide', '/media/knotty-cockpit-table', '/media/knotty-helm'],
    type: 'day',
    durationLabel: '8 hours',
    basePrice: 1600,
    priceUnit: 'flat',
    minNights: 0,
    capacityMin: 1,
    capacityMax: 12,
    includes: [
      "Knotty, a private 47' yacht with two staterooms",
      'Captain and crew',
      'Air-conditioned interior',
      'Shaded teak cockpit with dining table',
      'Bow sunpad and teak swim platform',
      'Tender aboard for shallow-water landings',
      'Wet bar at the helm',
      'Snorkeling and swim stops',
      'All-inclusive food and drinks',
      'Fuel and park fees',
    ],
    heroEmoji: '🛥️',
    accent: '#C2762F',
    active: true,
    sortOrder: 2,
  },
  {
    id: 'v_copper',
    boatName: 'Knotty',
    photo: '/media/knotty-cabin-night',
    gallery: ['/media/knotty-stern', '/media/knotty-cockpit-wide'],
    slug: 'copper-package',
    name: 'Copper Package — 4 Nights, 5 Days',
    tagline: 'Live aboard for four nights. Wake up somewhere new.',
    description:
      "Escape to paradise on an all-inclusive private yacht getaway. Four nights aboard a 47' two-stateroom yacht, mixing adventure and doing absolutely nothing, in whatever proportion you like.",
    type: 'multiday',
    durationLabel: '4 nights / 5 days',
    basePrice: 2000,
    priceUnit: 'per_night',
    minNights: 4,
    capacityMin: 2,
    capacityMax: 4,
    includes: [
      "47' two-stateroom yacht, exclusively yours",
      'Captain and crew for the full stay',
      'All meals and drinks aboard',
      'Daily snorkeling and island stops',
      'Fuel, mooring and park fees',
    ],
    heroEmoji: '🌅',
    accent: '#B06A3B',
    active: true,
    sortOrder: 3,
  },
  {
    id: 'v_silver',
    boatName: 'Knotty',
    photo: '/media/knotty-cockpit-wide',
    gallery: ['/media/knotty-cabin-night', '/media/knotty-stern'],
    slug: 'silver-package',
    name: 'Silver Package — 5 Nights, 6 Days',
    tagline: 'Two islands, five nights, one yacht that is only yours.',
    description:
      'Luxury and adventure across two islands. Five nights aboard, with the itinerary shaped around what your group actually wants to do — reefs, beaches, or a very slow lunch.',
    type: 'multiday',
    durationLabel: '5 nights / 6 days',
    basePrice: 2000,
    priceUnit: 'per_night',
    minNights: 5,
    capacityMin: 2,
    capacityMax: 4,
    includes: [
      "47' two-stateroom yacht, exclusively yours",
      'Two-island itinerary',
      'Captain and crew for the full stay',
      'All meals and drinks aboard',
      'Fuel, mooring and park fees',
    ],
    heroEmoji: '🏝️',
    accent: '#5B7F86',
    active: true,
    sortOrder: 4,
  },
  {
    id: 'v_gold',
    boatName: 'Knotty',
    photo: '/media/knotty-dinner-night',
    gallery: ['/media/knotty-cabin-night', '/media/lilknotty-running'],
    slug: 'gold-package',
    name: 'Gold Package — 6 Nights, 7 Days',
    tagline: 'The whole Caribbean week. Yacht, hotel, and a speedboat on the house.',
    description:
      'Experience the best of the Caribbean where opulence meets breathtaking natural beauty. Six nights split between the yacht and hotel stays, with a complimentary speedboat day included.',
    type: 'multiday',
    durationLabel: '6 nights / 7 days',
    basePrice: 2000,
    priceUnit: 'per_night',
    minNights: 6,
    capacityMin: 2,
    capacityMax: 4,
    includes: [
      "47' yacht plus hotel nights",
      'Complimentary speedboat day',
      'Captain and crew',
      'All meals and drinks aboard',
      'Fuel, mooring and park fees',
    ],
    heroEmoji: '👑',
    accent: '#C2953F',
    active: true,
    sortOrder: 5,
  },
]

// `photo` is the real corner of the boat this category happens in — the deck
// plan shows it when you load that zone.
export const categories = [
  { id: 'celebrate', label: 'Celebrate', blurb: 'Make the day mean something.', photo: '/media/knotty-cabin-night' },
  { id: 'eat_drink', label: 'Eat & Drink', blurb: 'Everything that comes on a tray.', photo: '/media/knotty-cockpit-table' },
  { id: 'adventure', label: 'Adventure', blurb: 'Things to do off the back of the boat.', photo: '/media/knotty-stern' },
  { id: 'comfort', label: 'Comfort & Care', blurb: 'The details that make a long day easy.', photo: '/media/knotty-cockpit-wide' },
]

// The gallery on the public page, in the order it reads best. `boat` labels
// each frame so nobody has to guess which vessel they are looking at.
export const gallery = [
  { src: '/media/lilknotty-running', boat: "Li'l Knotty", caption: 'On plane off the south shore. This is what most of the speedboat day looks like.' },
  { src: '/media/knotty-stern', boat: 'Knotty', caption: 'Knotty at the dock in French Harbour, tender ready on the teak platform.' },
  { src: '/media/knotty-cockpit-wide', boat: 'Knotty', caption: 'The shaded cockpit — where most of a charter day actually gets spent.' },
  { src: '/media/knotty-cockpit-table', boat: 'Knotty', caption: 'Teak table set for lunch, helm behind it.' },
  { src: '/media/knotty-helm', boat: 'Knotty', caption: 'Helm and wet bar. Ice, sink and the drinks within arm’s reach.' },
  { src: '/media/knotty-dinner-night', boat: 'Knotty', caption: 'Dinner aboard after dark, with the harbour lights behind you.' },
  { src: '/media/knotty-cabin-night', boat: 'Knotty', caption: 'The master stateroom, turned down for an overnight charter.' },
  { src: '/media/lilknotty-marina', boat: "Li'l Knotty", caption: 'Twin 200 hp Suzukis and a shark on the hull, tied up at the marina.' },
  { src: '/media/lilknotty-dusk', boat: "Li'l Knotty", caption: 'Dusk at the dock. Console lit, flag up, ready for the morning.' },
]

const extra = (id, category, emoji, name, price, unit, description, leadTimeHours = 48) => ({
  id,
  category,
  emoji,
  name,
  price,
  unit,
  description,
  leadTimeHours,
  active: true,
  maxQty: unit === 'per_person' ? 20 : 5,
})

export const extras = [
  // Celebrate
  extra('x_champagne', 'celebrate', '🍾', 'Champagne toast', 85, 'flat', 'A chilled bottle of Moët and proper glassware, poured wherever you tell the captain to stop.'),
  extra('x_flowers', 'celebrate', '🌺', 'Fresh flower setup', 120, 'flat', 'Tropical arrangements through the cabin and deck, cut the morning of your trip.'),
  extra('x_cake', 'celebrate', '🎂', 'Custom cake', 75, 'flat', 'Your message on it. Tell us the occasion and any allergies.', 72),
  extra('x_proposal', 'celebrate', '💍', 'Proposal setup', 350, 'flat', 'Deck lettering, petals, chilled champagne and a crew that knows exactly when to disappear.', 72),
  extra('x_turndown', 'celebrate', '🕯️', 'Cabin turndown', 160, 'flat', 'Rose petals, candles through the stateroom and a chilled bottle waiting. Overnight charters only.', 72),
  extra('x_photographer', 'celebrate', '📸', 'Photographer (2 hours)', 250, 'flat', 'A local photographer aboard, edited gallery delivered within 72 hours.'),
  extra('x_drone', 'celebrate', '🚁', 'Drone footage', 180, 'flat', 'Aerial video of the boat, the reef and your group, edited to a short film.'),
  extra('x_music', 'celebrate', '🎶', 'Live guitar', 200, 'flat', 'A local guitarist aboard for two hours of the trip.'),
  extra('x_playlist', 'celebrate', '🔊', 'Your playlist, our speakers', 0, 'flat', 'Send us your playlist before the trip and the boat is singing your songs when you step aboard. Free — music should be.', 24),
  extra('x_banner', 'celebrate', '🎉', 'Birthday deck party', 95, 'flat', 'Banner, balloons and a properly embarrassing crew singalong at cake time.', 48),
  extra('x_bottle_msg', 'celebrate', '💌', 'Message in a bottle', 30, 'flat', 'Write it aboard, seal it with wax, take it home — or let the sea have it. Your call.', 24),

  // Eat & Drink
  extra('x_lobster', 'eat_drink', '🦞', 'Lobster lunch', 65, 'per_person', 'Caribbean lobster grilled aboard, with plantain, rice and salad.'),
  extra('x_bbq', 'eat_drink', '🔥', 'Caribbean BBQ', 45, 'per_person', 'Grilled fish, chicken and pork with island sides, served on the water.'),
  extra('x_veg', 'eat_drink', '🥗', 'Vegetarian spread', 38, 'per_person', 'Grilled vegetables, fresh cheeses, hummus, breads and island fruit.'),
  extra('x_fruit', 'eat_drink', '🍍', 'Fruit and cheese table', 90, 'flat', 'A full spread of in-season island fruit, cheeses and crackers.'),
  extra('x_wine_red', 'eat_drink', '🍷', 'Red wine (bottle)', 55, 'flat', 'Malbec or Cabernet. Ask the crew for the current list.', 24),
  extra('x_wine_white', 'eat_drink', '🥂', 'White or rosé (bottle)', 55, 'flat', 'Sauvignon Blanc, Chardonnay or Provence rosé, served properly cold.', 24),
  extra('x_premium_bar', 'eat_drink', '🥃', 'Premium open bar', 40, 'per_person', 'Top-shelf rum, whiskey, gin and mixers for the whole trip.'),
  extra('x_bartender', 'eat_drink', '🍹', 'Cocktail bartender', 220, 'flat', 'A bartender aboard making frozen and classic cocktails to order.'),
  extra('x_prosecco', 'eat_drink', '🍾', 'Prosecco (bottle)', 48, 'flat', 'Cold, dry and dangerous in the sun. Ask for two.', 24),
  extra('x_michelada', 'eat_drink', '🍺', 'Michelada kit', 35, 'flat', 'Local beer, lime, spiced rim, and the crew\'s secret mix. The island cure for a hot afternoon.', 24),
  extra('x_rum_tasting', 'eat_drink', '🥃', 'Rum & chocolate tasting', 55, 'per_person', 'Five Honduran rums, island chocolate, and the captain\'s opinions — included at no charge.'),
  extra('x_ceviche', 'eat_drink', '🐟', 'Ceviche made on deck', 42, 'per_person', 'Caught in the morning, cured with lime in front of you. It does not get fresher.'),
  extra('x_coco', 'eat_drink', '🥥', 'Cold coconuts', 25, 'flat', 'A cooler of young coconuts, machete-opened on deck. Straw included, rum optional.', 24),

  // Adventure
  extra('x_tubing', 'adventure', '🛟', 'Tubing session', 60, 'flat', 'Towable tube and safety gear, as many runs as your group can take.', 24),
  extra('x_snorkel_extra', 'adventure', '🤿', 'Extra snorkel sets', 15, 'per_person', 'Additional masks, snorkels and fins beyond what the boat carries.', 24),
  extra('x_paddleboard', 'adventure', '🏄', 'Paddleboard', 45, 'flat', 'Inflatable SUP aboard for the day.', 24),
  extra('x_kayak', 'adventure', '🛶', 'Double kayak', 45, 'flat', 'Two-person kayak for exploring the mangroves and shallows.', 24),
  extra('x_fishing', 'adventure', '🎣', 'Fishing gear and guide', 150, 'flat', 'Rods, tackle and a crew member who knows where they are biting.'),
  extra('x_scuba', 'adventure', '🐠', 'Discover scuba (per diver)', 130, 'per_person', 'One guided dive on the reef with a certified instructor. No experience needed.', 72),
  extra('x_tender', 'adventure', '🛶', 'Tender island hop', 140, 'flat', 'Take the tender off the swim platform and land where the yacht cannot go — sandbars, mangrove cuts, an empty beach.'),
  extra('x_pigeon', 'adventure', '⛱️', 'Pigeon Cay beach stop', 120, 'flat', 'Add the sandbar and beach club stop to your route, entry included.', 24),
  extra('x_lilypad', 'adventure', '🛟', 'Floating lily pad', 55, 'flat', 'A giant floating mat off the stern. Holds the whole group, guarantees at least one great photo of someone falling off.', 24),
  extra('x_gopro', 'adventure', '🎥', 'Underwater camera', 65, 'flat', 'A GoPro aboard for the day, footage handed over on a drive before you step off.', 24),
  extra('x_snorkel_tour', 'adventure', '🐢', 'Turtle spotting run', 90, 'flat', 'The captain\'s own route over the grass flats where the turtles feed. No promises — a very good record.', 24),

  // Comfort & Care
  extra('x_pickup', 'comfort', '🚐', 'Hotel or cruise pickup', 60, 'flat', 'Air-conditioned round-trip transfer between your hotel or the cruise terminal and the marina.', 24),
  extra('x_massage', 'comfort', '💆', 'Massage aboard', 110, 'per_person', 'A licensed therapist aboard, 50 minutes on the shaded deck.', 72),
  extra('x_kids', 'comfort', '🧒', 'Family aboard set-up', 40, 'flat', 'Child-size life vests, pool floats, shaded seating and a snack tray, so the small crew is safe and busy all day.', 24),
  extra('x_towels', 'comfort', '🧺', 'Premium towels and shade', 35, 'flat', 'Oversized towels, extra umbrella and a cushioned bow setup.', 24),
  extra('x_cooler', 'comfort', '🧊', 'Extra cooler of drinks', 50, 'flat', 'A second stocked cooler of water, sodas and local beer.', 24),
  extra('x_wifi', 'comfort', '📶', 'WiFi aboard', 45, 'flat', 'Portable hotspot with island coverage for the trip.', 24),
  extra('x_hangover', 'comfort', '🧃', 'Morning-after kit', 28, 'flat', 'Electrolytes, cold towels, dark sunglasses and zero judgement. For day two of the packages.', 24),
  extra('x_robes', 'comfort', '🥽', 'His & hers robes', 40, 'flat', 'Soft robes for the cabin, yours to keep. Monogramming the boat\'s name, not yours — she earned it.', 48),
]

export const bundles = [
  {
    id: 'b_proposal',
    name: 'Proposal at Sea',
    tagline: 'Everything you need for the question, and nothing you have to think about.',
    emoji: '💍',
    photo: '/media/knotty-dinner-night',
    extraIds: ['x_proposal', 'x_champagne', 'x_flowers', 'x_photographer', 'x_music'],
    discountPct: 10,
    active: true,
  },
  {
    id: 'b_family',
    name: 'Family Day',
    tagline: 'Built for a boat with kids on it.',
    emoji: '👨‍👩‍👧',
    photo: '/media/knotty-cockpit-wide',
    extraIds: ['x_tubing', 'x_kids', 'x_bbq', 'x_snorkel_extra'],
    discountPct: 10,
    active: true,
  },
  {
    id: 'b_anniversary',
    name: 'Anniversary Sunset',
    tagline: 'Wine, dinner and the good light.',
    emoji: '🌇',
    photo: '/media/knotty-cabin-night',
    extraIds: ['x_wine_red', 'x_lobster', 'x_flowers', 'x_massage'],
    discountPct: 10,
    active: true,
  },
]

export const coupons = [
  {
    id: 'c_welcome',
    code: 'WELCOME10',
    type: 'percent',
    value: 10,
    minTotal: 1000,
    maxRedemptions: 100,
    redemptions: 0,
    expiresAt: null,
    active: true,
  },
]

export const blackouts = []
export const bookings = []
export const invoices = []
